#!/usr/bin/env bash
set -ex


if [[ -z "${CUDA_PATH}" ]] ; then
  CUDA_PATH="${1}" ; shift
fi

declare -a compile_distributed_interface=(
  "${GCC}" "-shared" "-std=c11" "-fPIC"
    "-I${CUDA_PATH}/include"
    "-I${PREFIX}/include"
    "-L${PREFIX}/lib"
  "distributed_interfaces/cutensornet_distributed_interface_mpi.c"
  "-o" "${PREFIX}/lib/libcutensornet_distributed_interface_mpi.so" "-lmpi"
)
"${compile_distributed_interface[@]}"
