#!/usr/bin/env bash
# shellcheck disable=SC1091
set -ex


if [[ -f "${RECIPE_DIR}/common/handle-files" ]] ; then
  source "${RECIPE_DIR}/common/handle-files"
else
  echo "error: common/handle-files is not available"
  exit 1
fi

conda clean --all --yes

{(
  
  declare -gx from named
  from="include" named="*cutensornet.h*" files move "${PREFIX}/include"
  from="include/cutensornet" named="*.h*" files move "${PREFIX}/include/cutensornet"
  
  from="lib" named="*cutensornet.so*" files move "${PREFIX}/lib"
)}



