#!/usr/bin/env bash

if [[ -n "${CONDA_CUDENSITYMAT_COMM_LIB}" ]]; then
  declare -gx CUDENSITYMAT_COMM_LIB="${CONDA_CUDENSITYMAT_COMM_LIB}"
  unset CONDA_CUDENSITYMAT_COMM_LIB
else
  unset CUDENSITYMAT_COMM_LIB
fi

if [[ -n "${CONDA_CUDENSITYMAT_MPI_COMM_LIB}" ]]; then
  declare -gx CUDENSITYMAT_MPI_COMM_LIB="${CONDA_CUDENSITYMAT_MPI_COMM_LIB}"
  unset CONDA_CUDENSITYMAT_MPI_COMM_LIB
else
  unset CUDENSITYMAT_MPI_COMM_LIB
fi

if [[ -n "${CONDA_CUDENSITYMAT_NCCL_COMM_LIB}" ]]; then
  declare -gx CUDENSITYMAT_NCCL_COMM_LIB="${CONDA_CUDENSITYMAT_NCCL_COMM_LIB}"
  unset CONDA_CUDENSITYMAT_NCCL_COMM_LIB
else
  unset CUDENSITYMAT_NCCL_COMM_LIB
fi
