#!/usr/bin/env bash
# shellcheck disable=SC1091
set -ex


if [[ -f "${RECIPE_DIR}/common/handle-files" ]] ; then
  source "${RECIPE_DIR}/common/handle-files"
else
  echo "error: common/handle-files is not available"
  exit 1
fi

conda clean --all --yes

{(

  declare -gx from named
  from="include" named="*cudensitymat.h*" files move "${PREFIX}/include"
  from="lib" named="*cudensitymat.so*" files move "${PREFIX}/lib"
)}
