#!/usr/bin/env bash
# shellcheck disable=SC1091
set -ex


if [[ -f "${RECIPE_DIR}/common/handle-files" ]] ; then
  source "${RECIPE_DIR}/common/handle-files"
else
  echo "error: common/handle-files is not available"
  exit 1
fi

conda clean --all --yes

{(

  declare -gx from named
  from="include" named="*cudensitymat.h*" files move "${PREFIX}/include"
  from="lib" named="*cudensitymat.so*" files move "${PREFIX}/lib"

  if [[ "${mpi}" != "nompi" ]]; then
  #if [[ -f "${PREFIX}/lib/libmpi.so" ]] ; then
    echo " mpi lib detected, building distributed interfaces" 
    # build the mpi wrapper lib  
    if ! [[ -f "distributed_interfaces/cudensitymat_distributed_interface_mpi.c" ]] ; then
      echo " error: distributed interface source not found in expected location "
      exit 1
    fi
    declare -a compile_command
    if [[ "${cuda_compiler_version}" == "11.8" ]]; then
      compile_command=(
         "${GCC}" "-shared" "-std=c99" "-fPIC"
          "-I${CUDA_PATH}/include" "-I${PREFIX}/include"
          "distributed_interfaces/cudensitymat_distributed_interface_mpi.c"
          "-L${PREFIX}/lib" "-lmpi"
          "-o" "${PREFIX}/lib/libcudensitymat_distributed_interface_mpi.so"
        )
    elif [[ "${cuda_compiler_version}" == "12.0" ]] ||  [[ "${cuda_compiler_version}" == "12.6" ]]; then
      compile_command=(
          "${GCC}" "-shared" "-std=c99" "-fPIC" ${CFLAGS} "-I${PREFIX}/include"
          "distributed_interfaces/cudensitymat_distributed_interface_mpi.c"
          "-L${PREFIX}/lib" "-lmpi"
          "-o" "${PREFIX}/lib/libcudensitymat_distributed_interface_mpi.so"
        )
    else
      echo "error: incompatible cuda version"
      exit 1
    fi
    echo "compile_command[@]"
    "${compile_command[@]}"
    if ! [[ -f "${PREFIX}/lib/libcudensitymat_distributed_interface_mpi.so" ]] ; then
      echo "error: cutensornet comm lib not in expected place"
      exit 1
    fi
    # copy activate/deactivate scripts
    mkdir -p "${PREFIX}/etc/conda/activate.d"
    cp "${RECIPE_DIR}/cudensitymat/cudm-activate.sh" "${PREFIX}/etc/conda/activate.d/cudm-activate.sh" 
    mkdir -p "${PREFIX}/etc/conda/deactivate.d"
    cp "${RECIPE_DIR}/cudensitymat/cudm-deactivate.sh" "${PREFIX}/etc/conda/deactivate.d/cudm-deactivate.sh"
  else
    echo " No mpi lib detected, not building distributed interfaces."
  fi
  
)}
