#!/usr/bin/env bash
set -ex

mkdir -p "${PREFIX}/etc/conda/activate.d"
mkdir -p "${PREFIX}/etc/conda/deactivate.d"
cp "cudensitymat/cudm-activate.sh" "${PREFIX}/etc/conda/activate.d/"
cp "cudensitymat/cudm-deactivate.sh" "${PREFIX}/etc/conda/deactivate.d/"
