#!/usr/bin/env bash

if [[ -n "${CONDA_CUPAULIPROP_COMM_LIB}" ]]; then
  declare -gx CUPAULIPROP_COMM_LIB="${CONDA_CUPAULIPROP_COMM_LIB}"
  unset CONDA_CUPAULIPROP_COMM_LIB
else
  unset CUPAULIPROP_COMM_LIB
fi

if [[ -n "${CONDA_CUPAULIPROP_MPI_COMM_LIB}" ]]; then
  declare -gx CUPAULIPROP_MPI_COMM_LIB="${CONDA_CUPAULIPROP_MPI_COMM_LIB}"
  unset CONDA_CUPAULIPROP_MPI_COMM_LIB
else
  unset CUPAULIPROP_MPI_COMM_LIB
fi

if [[ -n "${CONDA_CUPAULIPROP_NCCL_COMM_LIB}" ]]; then
  declare -gx CUPAULIPROP_NCCL_COMM_LIB="${CONDA_CUPAULIPROP_NCCL_COMM_LIB}"
  unset CONDA_CUPAULIPROP_NCCL_COMM_LIB
else
  unset CUPAULIPROP_NCCL_COMM_LIB
fi
