azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 10GiB
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
idle_timeout_minutes: 60
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test: native